### ISSUE TITLE
UBSAN_SANITIZE_ADDRESS_SUPPORTED

### ISSUE THREAD

**Issue by dolby360z** [siriobalmelli/nrf_mesh_4.0.0_lpn_SAR#1]
Hi.
I got -- Performing Test UBSAN_SANITIZE_ADDRESS_SUPPORTED - Failed
check_c_compiler_flag("-fsanitize=address" UBSAN_SANITIZE_ADDRESS_SUPPORTED)

Maybe you should use 
check_c_compiler_flag(-static-libasan UBSAN_SANITIZE_ADDRESS_SUPPORTED)

**Comment by siriobalmelli** [comment]
Thank you for your issue.

This repo was originally constructed to show a bug to Nordic Semiconductors in their mesh SDK v4.0.0 (see bug [here](https://devzone.nordicsemi.com/f/nordic-q-a/56546/mesh-stack-throws-nrf_mesh_evt_sar_failed-when-lpn-replies-to-a-publication-set-message-via-friend-node)), which has since been closed.

Also, their mesh SDK has since had 2 releases, the latest version at this time is 4.2.0 which you can get [here](https://www.nordicsemi.com/-/media/Software-and-other-downloads/SDKs/nRF5-SDK-for-Mesh/nrf5SDKforMeshv420src.zip).

So, this repo here should have been archived - it is no longer current; my apologies for leaving it open.

I am closing the issue and archiving the repo, but if you run into trouble go ahead and post on [Nordic's DevZone](https://devzone.nordicsemi.com/) or on [their GitHub page](https://github.com/NordicSemiconductor).
